#https://computing.docs.ligo.org/gitlab-ci-templates/
#https://github.com/conda/conda-build/issues/4976
include:
  - local: '.gitlab/conda.yml'

stages:
  - test
  - build

default:
  image: condaforge/miniforge3:latest
  #image: continuumio/miniconda3:latest
# cache is slow for many files
#  cache:
#    key:
#      files:
#        - environment.yml
#    paths:
#      - .env/

.parallel-hidden-job:
  extends:
    - .conda:base
  before_script:
    - !reference [ ".conda:base", before_script ]
    - echo "Current directory is $(pwd)"
    - echo "HOME is $HOME"
    - echo "PATH is $PATH"
    - echo "User is $USER"
    - echo "Hostname is $(hostname)"
  parallel:
    matrix:
      - VERSION: [ '38', '311' ]

#build-job:
#  extends: .parallel-hidden-job
#  stage: test
#  when: manual
#  script:
#    - python3 -V
#    - python3 -m pip install virtualenv
#    - rm -rf venv$VERSION
#    - virtualenv venv$VERSION
#    - source venv$VERSION/bin/activate
#    - echo "Building and setting up"
#    - python3 -m pip install pytest
#    - pip install -r requirements.txt

test-job-conda:
  stage: test
  extends: .parallel-hidden-job
  script:
    - python3 -V
    - conda -V
    - rm -rf .env$VERSION
    - echo "Building and setting up from environment.yml"
    - conda env create -f .gitlab/environment$VERSION.yml -n venv$VERSION
    - conda activate venv$VERSION
    - pip install pytest
    - pip install --no-dependencies .
    - echo "Running tests"
    - conda activate venv$VERSION
    - pytest -rxs
    - echo "Done"

conda-build:
  stage: build
  extends:
    - .conda:build
  variables:
    MAMBABUILD: "true"

wheel-build:
  stage: build
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  script:
    - python3 -V
    - python3 -m pip install virtualenv
    - rm -rf venv
    - virtualenv venv
    - source venv/bin/activate
    - echo "Building and setting up"
    - pip install -r requirements.txt
    - python setup.py bdist_wheel
    - echo "Done wheel build"
  artifacts:
    paths:
      - dist/*.whl

